### ISSUE TITLE
[Global UI] Incorrect logo shows when switching between apps

### ISSUE THREAD

**Issue by nessamilan** [covidsafe/App-iOS#267]
Version 1.09

**Problem**: When switching between apps, the old CovidSafe logo appears instead of the new CommonCircle logo

**Solution**: Update to new logo

<img width="385" alt="Screen Shot 2020-07-09 at 4 19 39 PM" src="https://user-images.githubusercontent.com/6819397/87100061-40bae480-c200-11ea-8f6d-836958f9a785.png">

**Comment by cheng-tan** [comment]
@nessamilan Can you upgrade to 1.11 and try again. This might have been fixed.

**Comment by nessamilan** [comment]
As of 3:47pm it was still showing old icon.

<img width="427" alt="Screen Shot 2020-07-10 at 2 56 19 PM" src="https://user-images.githubusercontent.com/6819397/87205973-8984a300-c2bd-11ea-8e80-89232cd2049d.png">

**Comment by cheng-tan** [comment]
So far, cannot reproduce this issue

**Comment by nessamilan** [comment]
@cheng-tan Now looks correct in 1.13 on iOS and Android.
